version: "3.9"

services:
  postgresql:
    image: postgres:12.16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./volumes/postgresql:/var/lib/postgresql/data
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4:latest
    user: root
    restart: always
    env_file:
      - .env
    ports:
      - "8888:80"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql
    networks:
      - db-network

networks: 
  db-network:
    driver: bridge